# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gr_cov_cpp <- function(x, gr_means, kk, pp, ntp, n_vec) {
    .Call(`_gmtFD_gr_cov_cpp`, x, gr_means, kk, pp, ntp, n_vec)
}

